version: "3.9"
x-base: &base
  build: .
  env_file: .env
  volumes:
    - ./reports:/reports
services:
  eval:
    <<: *base
    # docker compose run eval
    # docker compose run eval --eos-runs 1000
    # docker compose run eval --section interface
    # docker compose run eval --section accuracy --full-accuracy
  eval-eos:
    <<: *base
    command: ["--eos-runs", "1000"]
  eval-accuracy:
    <<: *base
    command: ["--section", "accuracy", "--full-accuracy"]
